android_binary(
    name = "app",
    custom_package = "com.morfly.helloworld",
    manifest = "AndroidManifest.xml",
    srcs = ["java/com/morfly/helloworld/MainActivity.java"],
    resource_files = glob(["res/**"]),
)